name: "docker pg build"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # platforms: ${{ matrix.platforms }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ghcr.io/x-b-e/server-pg:15
          build-args: |
            PG_MAJOR="15"
            PG_TAG="15-3.4""
          # outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=XBE server pg
          # cache-from: ghcr.io/x-b-e/server-pg
